from typing import Any, Optional
from pydantic import BaseModel, ConfigDict, Field
class PredictRequest(BaseModel):
    """Features of a customer for prediction of term-deposit subscription."""
    age: int = Field(..., description="Customer age", json_schema_extra={"example": 30})
    job: str = Field(..., description="Type of job", json_schema_extra={"example": "blue-collar"})
    marital: str = Field(..., description="Marital status", json_schema_extra={"example": "married"})
    education: str = Field(..., description="Education level", json_schema_extra={"example": "secondary"})
    default: str = Field(..., description="Has credit in default?", json_schema_extra={"example": "no"})
    balance: int = Field(..., description="Average yearly balance in euros", json_schema_extra={"example": 1500})
    housing: str = Field(..., description="Has housing loan?", json_schema_extra={"example": "yes"})
    loan: str = Field(..., description="Has personal loan?", json_schema_extra={"example": "no"})
    contact: str = Field("unknown", description="Contact communication type", json_schema_extra={"example": "cellular"})
    day: int = Field(15, description="Last contact day of the month", json_schema_extra={"example": 15})
    month: str = Field(..., description="Last contact month of year", json_schema_extra={"example": "may"})
    campaign: int = Field(1, description="Number of contacts performed during this campaign", json_schema_extra={"example": 1})
    pdays: int = Field(-1, description="Days after last contact from a previous campaign (-1 means not contacted)", json_schema_extra={"example": -1})
    previous: int = Field(0, description="Number of contacts performed before this campaign", json_schema_extra={"example": 0})
    poutcome: str = Field("unknown", description="Outcome of the previous marketing campaign", json_schema_extra={"example": "unknown"})
    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "age": 32,
                "job": "management",
                "marital": "single",
                "education": "tertiary",
                "default": "no",
                "balance": 2343,
                "housing": "yes",
                "loan": "no",
                "contact": "cellular",
                "day": 5,
                "month": "may",
                "campaign": 1,
                "pdays": -1,
                "previous": 0,
                "poutcome": "unknown"
            }
        }
    )
class PredictResponse(BaseModel):
    """Output prediction for term-deposit subscription."""
    prediction: int = Field(..., description="Binary prediction (1 = subscribed, 0 = not)")
    probability: float = Field(..., description="Model conversion probability (0.0 to 1.0)")
    threshold_decision: bool = Field(..., description="Decision based on standard threshold (e.g. >= 0.40)")
    model_version: str = Field(..., description="Identifier of the serving model")
class BatchScoreRecordResponse(BaseModel):
    """Scored row response."""
    record_index: int
    prediction: int
    probability: float
    conversion_band: str
class BatchScoreRequest(BaseModel):
    """Batch scoring payload consisting of multiple customer records."""
    records: list[PredictRequest] = Field(..., description="List of customer records to score")
class BatchScoreResponse(BaseModel):
    """Response of a batch scoring operation."""
    scores: list[BatchScoreRecordResponse]
    summary: dict[str, int] = Field(..., description="Counts of predictions by conversion bands")
    model_version: str
class AskComplaintsRequest(BaseModel):
    """Question about CFPB complaints with optional filters."""
    query: str = Field(..., description="The query to ask", json_schema_extra={"example": "What are the main issues with credit reports?"})
    filters: Optional[dict[str, Any]] = Field(
        None,
        description="Optional filters (product, company, date_start, date_end, issue)",
        json_schema_extra={"example": {"product": "Credit reporting", "company": "Equifax"}}
    )
class AskComplaintsResponse(BaseModel):
    """Response of a grounded Q&A query."""
    answer: str = Field(..., description="The answer generated by Gemini")
    evidence_ids: list[str] = Field(..., description="List of Complaint IDs used as context")
    evidence_sufficiency: str = Field(..., description="Quality of context evidence (HIGH | MEDIUM | LOW | NONE)")
    prompt_version: str = Field(..., description="Version of the grounding prompt template")
class CustomerIntelRequest(BaseModel):
    """Combined ML predict + RAG context request for customer insights."""
    customer_features: PredictRequest = Field(..., description="Customer features for ML prediction")
    complaint_filters: Optional[dict[str, Any]] = Field(
        None,
        description="Optional filters to retrieve matching complaint themes",
        json_schema_extra={"example": {"company": "Equifax"}}
    )
class CustomerIntelResponse(BaseModel):
    """Combined customer insights containing conversion probability and complaint themes."""
    conversion_band: str = Field(..., description="Conversion priority band (HIGH | MEDIUM | LOW)")
    probability: float = Field(..., description="Model subscription probability")
    top_complaint_themes: list[dict[str, Any]] = Field(
        ...,
        description="List of matching retrieved complaints showing pain points"
    )
    model_version: str
    index_version: str
class HealthResponse(BaseModel):
    """Service status and component version details."""
    status: str = Field("healthy", description="Status of the application")
    model_version: str = Field(..., description="Loaded ML model version description")
    index_version: str = Field(..., description="Loaded FAISS vector index version description")
    uptime_seconds: float = Field(..., description="Uptime of the server in seconds")
class MetricsResponse(BaseModel):
    """Prometheus-style and diagnostic counters and distributions."""
    uptime_seconds: float
    request_counts: dict[str, int]
    error_counts: dict[str, int]
    latencies_ms: dict[str, float]
    predictions_count: dict[str, int]
    rag_retrievals_count: int
    rag_avg_evidence_count: float
